Fix numpy ABI compatible and Use CIBuildWheel and github action to build python wheels automatically (#67)
* use oldest-supported-numpy; adjust cypthon install requirement setup

* add cibuildwheel in github action

* change the numpy range to 1.14.5, according to the oldest_support_numpy https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg\#L54

* change numpy version in setup.py

* test override numpy version for python 3.7

* update matrix os variables

* remove unnecessary setup requirement in setup.py

* fix typo?

* add 3.6

* workaround for error in windows os: CCompiler_spawn() got an unexpected keyword argument https://github.com/pypa/distutils/issues/15\#issuecomment-685029840

* skip pypy 3.7 macos, due to error would build wheel with unsupported tag pp37 pypy37_pp73  macosx_10_9_x86_64

* add pytest after build

* add pytest folder

* add CIBW archs

* indicate tests folder explicitly

* fix test in CIBW

* skip pypy37 for mac linux and window

* also skip other pypy for mac linux and window

* skip all pypy for mac linux and window

* test cibuildwheel 2.6.1, since 2.7 gives  standard_init_linux.go:228: exec user process caused: exec format error

* try use python -m to see if can workaroudn the aarch64 error

* use different pytest command

* skip linux aarch64

* change version name to 0.3.2rc3

* fix musllinux No lapack/blas resources found

* skip musllinux

* add pypi into release destination

* update version and update release strategy

* update version and readme

Co-authored-by: Zhe Sun <info@sun-analytics.nl>
Co-authored-by: Stephane Collot <stephane.collot@ing.com>